# Generated by Django 3.1.7 on 2021-03-01 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['-date_created', '-priority']},
        ),
        migrations.RemoveField(
            model_name='todo',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='created',
        ),
        migrations.AddField(
            model_name='todo',
            name='date_created',
            field=models.DateField(default='2021-03-01'),
        ),
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')], default=1),
        ),
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.BooleanField(choices=[(False, 'In Progress'), (True, 'Completed')], default=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='due_date',
            field=models.DateField(default='2021-03-01'),
        ),
    ]
